//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clothes> Clothes { get; set; }
        public virtual DbSet<ClothingType> ClothingType { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<Frequencies> Frequencies { get; set; }
        public virtual DbSet<Incomes> Incomes { get; set; }
        public virtual DbSet<LinkSuitClothes> LinkSuitClothes { get; set; }
        public virtual DbSet<Suit> Suit { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
